module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "scope-enum": [
      2,
      "always",
      [
        "blog",
        "proj",
        "lib",
        "package",
        "config",
        "deps",
        "ui",
        "components",
        "pages",
        "api",
        "styles",
        "assets",
        "seo",
        "analytics",
        "scripts",
        "commitlint",
        "husky",
        "eslint",
        "typescript",
        "tailwind",
        "vercel",
      ],
    ],
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "chore",
        "style",
        "refactor",
        "ci",
        "update",
        "test",
        "perf",
        "revert",
        "vercel",
        "script",
      ],
    ],
  },
};
