import { MdOutlineEmojiEvents } from "react-icons/md";
import { MdEventAvailable } from "react-icons/md";
import { MdEvent } from "react-icons/md";
import { VscSymbolEvent } from "react-icons/vsc";
import { MdTimeline } from "react-icons/md";
import { RiMapPinTimeLine } from "react-icons/ri";
import { MdEventNote } from "react-icons/md";
import { SiHiveBlockchain } from "react-icons/si";
import { SiChainlink } from "react-icons/si";
import { IoIosRocket } from "react-icons/io";

const timelineDetails = [
  {
    timeline_title: "fastn Roadshow Bangalore",
    timeline_description: "",
    timeline_icon: <SiChainlink />,
    timeline_place: "Bangalore",
    timeline_date: "19th August 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "fastn Roadshow Kolkata",
    timeline_description: "",
    timeline_icon: <VscSymbolEvent />,
    timeline_place: "Indore",
    timeline_date: "12th August 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "red.400",
  },
  {
    timeline_title: "fastn Roadshow Delhi",
    timeline_description: "",
    timeline_icon: <IoIosRocket />,
    timeline_place: "Delhi",
    timeline_date: "06th June 2023",
    timeline_day: "Sunday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "purple.400",
  },
  {
    timeline_title: "fastn Roadshow Nagpur",
    timeline_description: "",
    timeline_icon: <MdTimeline />,
    timeline_place: "Nagpur",
    timeline_date: "29th June 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "blue.400",
  },
  {
    timeline_title: "fastn Roadshow Mumbai",
    timeline_description: "",
    timeline_icon: <RiMapPinTimeLine />,
    timeline_place: "Mumbai",
    timeline_date: "22nd June 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "red.400",
  },
  {
    timeline_title: "fastn Roadshow Jaipur",
    timeline_description: "",
    timeline_icon: <MdEventAvailable />,
    timeline_place: "Jaipur",
    timeline_date: "15th July 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "fastn Roadshow Ahmedabad",
    timeline_description: "",
    timeline_icon: <VscSymbolEvent />,
    timeline_place: "Ahmedabad",
    timeline_date: "08th July 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "teal.400",
  },
  {
    timeline_title: "fastn Roadshow Ujjain",
    timeline_description: "",
    timeline_icon: <MdEvent />,
    timeline_place: "Ujjain",
    timeline_date: "01st July 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "purple.400",
  },
  {
    timeline_title: "fastn Roadshow Lucknow",
    timeline_description: "",
    timeline_icon: <MdTimeline />,
    timeline_place: "Lucknow",
    timeline_date: "24th June 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "blue.400",
  },
  {
    timeline_title: "fastn Roadshow Bhopal",
    timeline_description: "",
    timeline_icon: <SiChainlink />,
    timeline_place: "Bhopal",
    timeline_date: "17th June 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "fastn Roadshow Indore",
    timeline_description: "",
    timeline_icon: <VscSymbolEvent />,
    timeline_place: "Indore",
    timeline_date: "10th June 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://twitter.com/ayushsoni1010",
    timeline_tags: [
      { tag: "fastn" },
      { tag: "Framework" },
      { tag: "Open Source" },
      { tag: "Portfolio" },
      { tag: "FifthTry" },
      { tag: "Events" },
      { tag: "DevRel" },
      { tag: "Roadshow" },
    ],
    timeline_card_color: "red.400",
  },
  {
    timeline_title: "DevRel Meetup in Bangalore",
    timeline_description: "",
    timeline_icon: <MdEventAvailable />,
    timeline_place: "Bangalore",
    timeline_date: "3rd June 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Atsushi",
    timeline_event_link: "https://twitter.com/goofmint",
    timeline_tags: [
      { tag: "Developers" },
      { tag: "Meetup" },
      { tag: "Community" },
      { tag: "GitHub" },
      { tag: "DevRel" },
      { tag: "Open Source" },
    ],
    timeline_card_color: "teal.400",
  },
  {
    timeline_title: "JavaSript Conference India 2023",
    timeline_description: "",
    timeline_icon: <IoIosRocket />,
    timeline_place: "Bangalore",
    timeline_date: "2nd June 2023",
    timeline_day: "Friday",
    timeline_hostedby: "JS Conference India",
    timeline_event_link: "https://jsconf.in/",
    timeline_tags: [
      { tag: "JavaScript" },
      { tag: "Conference" },
      { tag: "India" },
      { tag: "Community" },
      { tag: "Open Source" },
    ],
    timeline_card_color: "purple.400",
  },
  {
    timeline_title: "Cloud Security & Observability Data Meetup",
    timeline_description: "",
    timeline_icon: <MdEventNote />,
    timeline_place: "Microsoft Reactor, Bangalore",
    timeline_date: "31st May 2023",
    timeline_day: "Wednesday",
    timeline_hostedby: "Aravind Putrevu",
    timeline_event_link: "https://www.linkedin.com/in/avinash-dalvi-315b021a/",
    timeline_tags: [
      { tag: "Data Ingestion" },
      { tag: "Monitoring" },
      { tag: "Observability" },
      { tag: "Cloud" },
      { tag: "Open Source" },
      { tag: "Security" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "BNB Chain Innovation Roadshow - Indore",
    timeline_description: "",
    timeline_icon: <SiHiveBlockchain />,
    timeline_place: "Indore",
    timeline_date: "13th May 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "BNB Chain",
    timeline_event_link: "https://www.bnbchain.org/en",
    timeline_tags: [
      { tag: "BNB Chain" },
      { tag: "Blockchain" },
      { tag: "Community" },
      { tag: "JavaScript" },
      { tag: "Contracts" },
      { tag: "Dynamic NFT" },
      { tag: "Solidity" },
    ],
    timeline_card_color: "teal.400",
  },
  {
    timeline_title: "Developer's Coffee Meetup",
    timeline_description: "",
    timeline_icon: <MdTimeline />,
    timeline_place: "Indore",
    timeline_date: "6th May 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Ayush Soni",
    timeline_event_link: "https://lu.ma/dev-coffee-meetup",
    timeline_tags: [
      { tag: "Developers" },
      { tag: "Community" },
      { tag: "Software Development" },
      { tag: "Web3" },
      { tag: "Meetup" },
      { tag: "DevRel" },
      { tag: "Open Source" },
    ],
    timeline_card_color: "blue.400",
  },
  {
    timeline_title: "CoinDCX Indore Chapter - Creator Economy in Web3",
    timeline_description: "",
    timeline_icon: <RiMapPinTimeLine />,
    timeline_place: "Indore",
    timeline_date: "30th April 2023",
    timeline_day: "Sunday",
    timeline_hostedby: "CoinDCX",
    timeline_event_link: "https://coindcx.com",
    timeline_tags: [
      { tag: "CoinDCX" },
      { tag: "Web3" },
      { tag: "Bitcoin" },
      { tag: "Indore Chapter" },
      { tag: "Creator Economy" },
      { tag: "Blockchain" },
      { tag: "Community Space" },
    ],
    timeline_card_color: "red.400",
  },
  {
    timeline_title: "Wittyhacks 3.0 Hackathon",
    timeline_description: "",
    timeline_icon: <MdEventAvailable />,
    timeline_place: "NMIMS Indore",
    timeline_date: "07th - 9th April 2023",
    timeline_day: "Friday - Sunday",
    timeline_hostedby: "Wittyhacks",
    timeline_event_link: "https://wittyhacks.in/",
    timeline_tags: [
      { tag: "Wittyhacks" },
      { tag: "fastn" },
      { tag: "Open Source" },
      { tag: "Datacode" },
      { tag: "Projects" },
      { tag: "Hackathon" },
      { tag: "DevRel" },
      { tag: "Community" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "Blockmeet - Indore",
    timeline_description: "",
    timeline_icon: <VscSymbolEvent />,
    timeline_place: "Indore",
    timeline_date: "18th March 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Blockmeet Chapters",
    timeline_event_link: "https://foundershiphq.com/",
    timeline_tags: [
      { tag: "Blockmeet" },
      { tag: "Foundership" },
      { tag: "Community" },
      { tag: "Meetup" },
      { tag: "Blockchain" },
    ],
    timeline_card_color: "teal.400",
  },
  {
    timeline_title: "The Product Folks - Grab Chai Offline Meetup",
    timeline_description: "",
    timeline_icon: <MdEvent />,
    timeline_place: "Indore",
    timeline_date: "18th March 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "The Product Folks",
    timeline_event_link: "https://www.theproductfolks.com/",
    timeline_tags: [
      { tag: "TPF" },
      { tag: "Product Managers" },
      { tag: "Community" },
      { tag: "Meetup" },
      { tag: "Testing" },
      { tag: "Product" },
    ],
    timeline_card_color: "purple.400",
  },
  {
    timeline_title: "Bhopal FOSS",
    timeline_description:
      "Met with fellow developers and engaged in the panel discussions. Learned about Keploy services and got to know about Stage which is basically a OTT app and different mobile/desktop compabilities while building cross platforms apps using Flutter.",
    timeline_icon: <MdEventAvailable />,
    timeline_place: "Bhopal",
    timeline_date: "5th March 2023",
    timeline_day: "Sunday",
    timeline_hostedby: "FOSS - Free and Open-Source Software",
    timeline_event_link: "https://github.com/foss-dev",
    timeline_tags: [
      { tag: "FOSS" },
      { tag: "Conference" },
      { tag: "Flutter" },
      { tag: "Community" },
      { tag: "GitHub" },
      { tag: "E2E Testing" },
      { tag: "Cloud" },
      { tag: "JavaScript" },
      { tag: "Apache" },
    ],
    timeline_card_color: "teal.400",
  },
  {
    timeline_title: "Hack This Fall 3.0",
    timeline_description:
      "Hack This Fall 3.0 was the first in-person hackathon attended in Gujarat, Gandhinagar organized by Hack This Fall and Major League Hacking community. I met with fellow hackers, organizers, and other amazing like-minded folks. It was a 36hours long hackathon and my team HEKORS won the prize for the Most Creative Use of Twilio and enjoyed all the amazing activities",
    timeline_icon: <MdOutlineEmojiEvents />,
    timeline_place: "Gandhinagar",
    timeline_date: "3rd - 5th February 2023",
    timeline_day: "Friday - Sunday",
    timeline_hostedby: "Hack This Fall",
    timeline_event_link: "https://hackthisfall.tech/",
    timeline_tags: [
      { tag: "MLH" },
      { tag: "Hackathon" },
      { tag: "HTF 3.0" },
      { tag: "Community" },
      { tag: "GitHub" },
      { tag: "Web3" },
      { tag: "AR/VR" },
      { tag: "Cloud" },
      { tag: "Blockchain" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "Developer's Brunch - Indore",
    timeline_description:
      "I deep down into various chains and learned about the BNB chain. Surrounded by the web3 people at the meetup, I connected and had great networking with many folks out there. It was an amazing web3 event and got cool swags.",
    timeline_icon: <SiChainlink />,
    timeline_place: "Indore",
    timeline_date: "28th January 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Build N Build",
    timeline_event_link: "https://www.bnbchain.org/en",
    timeline_tags: [
      { tag: "BNB Chain" },
      { tag: "Web3" },
      { tag: "Crypto" },
      { tag: "Community" },
      { tag: "Blockchain" },
      { tag: "Chains" },
      { tag: "dApps" },
    ],
    timeline_card_color: "cyan.400",
  },
  {
    timeline_title: "Experiential Learning, OmniStudio and Test Automation",
    timeline_description:
      "Again, heads up to the Trailblazer community for organizing such amazing events where I deep down into the learnings on Lightning Web Components, OmniStudio, etc. Met with various people at the event, and enjoyed the activities where teams faced challenges and rewarded amazing swags.",
    timeline_icon: <IoIosRocket />,
    timeline_place: "Indore",
    timeline_date: "21st January 2023",
    timeline_day: "Saturday",
    timeline_hostedby: "Salesforce",
    timeline_event_link: "https://www.salesforce.com/in/",
    timeline_tags: [
      { tag: "Salesforce" },
      { tag: "Trailblazer" },
      { tag: "Community" },
      { tag: "OmniStudio" },
      { tag: "Lightning Web Components" },
      { tag: "Testing" },
      { tag: "Automation" },
    ],
    timeline_card_color: "purple.400",
  },
  {
    timeline_title: "DevFest 2022",
    timeline_description:
      "It was an amazing experience meeting with the experts and other speakers at DevFest Indore 2022 hosted by Google Developer Groups Indore. I met with many folks at the event and mentored the same. I learned about various things related to flutter, game, and android development.",
    timeline_icon: <RiMapPinTimeLine />,
    timeline_place: "Indore",
    timeline_date: "03rd - 04th December 2022",
    timeline_day: "Sunday",
    timeline_hostedby: "Google Developer Groups",
    timeline_event_link: "https://devfest.gdgindore.in/",
    timeline_tags: [
      { tag: "Game Development" },
      { tag: "Andriod" },
      { tag: "Flutter" },
      { tag: "Community Space" },
      { tag: "JavaScript" },
      { tag: "DevFest Indore" },
    ],
    timeline_card_color: "red.400",
  },
  {
    timeline_title: "Developers India Tour",
    timeline_description:
      "This event was more about creating the hands-on contract and getting an NFT. Got some insights about the Solana chain and build projects using JavaScript. I mentored and helped many folks in project building and connected with the people.",
    timeline_icon: <SiHiveBlockchain />,
    timeline_place: "Bhopal",
    timeline_date: "18th November 2022",
    timeline_day: "Friday",
    timeline_hostedby: "Solana",
    timeline_event_link: "https://solana.com/",
    timeline_tags: [
      { tag: "Solana" },
      { tag: "Blockchain" },
      { tag: "Community" },
      { tag: "JavaScript" },
      { tag: "Contracts" },
      { tag: "NFT" },
    ],
    timeline_card_color: "teal.400",
  },
  {
    timeline_title: "#RoadToPolygonConnect Polygon Guild Jaipur",
    timeline_description:
      "Another web3 event excited me about polygon solutions and different chains and networks in the market. I was curious to know more about centralized and decentralized applications, and layers in web3. I was surrounded by a bunch of web3 people who are building communities and cool applications.",
    timeline_icon: <MdEventNote />,
    timeline_place: "Jaipur",
    timeline_date: "6th November 2022",
    timeline_day: "Sunday",
    timeline_hostedby: "Polygon",
    timeline_event_link: "https://polygon.technology/",
    timeline_tags: [
      { tag: "Polygon" },
      { tag: "Blockchain" },
      { tag: "Web3" },
      { tag: "Ethereum" },
      { tag: "Guild" },
      { tag: "Community" },
      { tag: "dApps" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "AWS Community Day Rajasthan",
    timeline_description:
      "A community meetup for all the people who are getting started and experienced with AWS. I connected with various people who are working professionally in cloud computing, learned new things about AWS services, and explored the city.",
    timeline_icon: <MdTimeline />,
    timeline_place: "Jaipur",
    timeline_date: "5th November 2022",
    timeline_day: "Saturday",
    timeline_hostedby: "Amazon Web Services",
    timeline_event_link: "https://awsugjaipur.in/",
    timeline_tags: [
      { tag: "AWS" },
      { tag: "Community" },
      { tag: "Software Development" },
      { tag: "Cloud Native" },
      { tag: "Conference" },
      { tag: "DevOps" },
      { tag: "Open Source" },
    ],
    timeline_card_color: "blue.400",
  },
  {
    timeline_title: "CoinDCX Indore Bitcoin Whitepaper Day Meetup",
    timeline_description:
      "As the name signifies Bitcoin, I dive deeper into cryptocurrencies and blockchain and reminded me of Satoshi Nakamoto. I met with amazing folks, founders, and speakers who changed my perspective on Web3, dApps, etc., and discussed further building web3 communities and projects.",
    timeline_icon: <RiMapPinTimeLine />,
    timeline_place: "Indore",
    timeline_date: "30th October 2022",
    timeline_day: "Sunday",
    timeline_hostedby: "CoinDCX",
    timeline_event_link: "https://coindcx.com",
    timeline_tags: [
      { tag: "CoinDCX" },
      { tag: "Web3" },
      { tag: "Bitcoin" },
      { tag: "Indore Chapter" },
      { tag: "Whitepaper" },
      { tag: "Ethereum" },
      { tag: "Community Space" },
    ],
    timeline_card_color: "red.400",
  },
  {
    timeline_title: "Trailblazer Community Indore Diwali Meetup",
    timeline_description:
      "This was one of the first events, I got to know various things about Salesforce and the Trailblazer community of the Salesforce Developer Groups at Indore. It provides customer relationship management software and applications focused on sales, customer service, marketing automation, analytics, and application development. ",
    timeline_icon: <VscSymbolEvent />,
    timeline_place: "Indore",
    timeline_date: "29th October 2022",
    timeline_day: "Saturday",
    timeline_hostedby: "Salesforce",
    timeline_event_link: "https://www.salesforce.com/in/",
    timeline_tags: [
      { tag: "Salesforce" },
      { tag: "Trailblazer" },
      { tag: "Lightning Web Components" },
      { tag: "Event" },
      { tag: "Cloud Computing" },
    ],
    timeline_card_color: "teal.400",
  },
  {
    timeline_title: "HotWax Hacktoberfest Meetup",
    timeline_description:
      "Again, heads up with another meetup of Hacktoberfest. I contributed to various open-source projects, got exciting goodies and swags from the HotWax team, collaborated with the people at the event, and learned something new.",
    timeline_icon: <MdEvent />,
    timeline_place: "Indore",
    timeline_date: "14th October 2022",
    timeline_day: "Friday",
    timeline_hostedby: "HotWax Systems",
    timeline_event_link: "https://mlh.io/",
    timeline_tags: [
      { tag: "HotWax" },
      { tag: "Open Source" },
      { tag: "Hacktoberfest" },
      { tag: "Contribution" },
      { tag: "Meetup" },
      { tag: "Projects" },
    ],
    timeline_card_color: "purple.400",
  },
  {
    timeline_title: "Getting started with Open Source",
    timeline_description:
      "It was the time of Hacktoberfest, I had contributed to open-source projects, collaborate with amazing folks in the community, and learned new things. All the things were around Open Source and contributions to the Hacktoberfest 2022 program.",
    timeline_icon: <MdEventAvailable />,
    timeline_place: "Indore",
    timeline_date: "08th October 2022",
    timeline_day: "Saturday",
    timeline_hostedby: "Datacode",
    timeline_event_link: "https://datacode.in/",
    timeline_tags: [
      { tag: "Datacode" },
      { tag: "Hacktoberfest" },
      { tag: "Open Source" },
      { tag: "Projects" },
      { tag: "Contribution" },
      { tag: "Community" },
    ],
    timeline_card_color: "orange.400",
  },
  {
    timeline_title: "MLH HackCon IN",
    timeline_description:
      "MLH HackCon was the first conference in India organized by Major League Hacking community. I met with fellow hackers, GitHub Campus Experts, the MLH team, and other amazing like-minded folks. This was the first conference I had ever attended and enjoyed all the amazing activites and after party sessions.",
    timeline_icon: <MdOutlineEmojiEvents />,
    timeline_place: "Delhi",
    timeline_date: "24th September 2022",
    timeline_day: "Sunday",
    timeline_hostedby: "Major League Hacking",
    timeline_event_link: "https://mlh.io/",
    timeline_tags: [
      { tag: "MLH" },
      { tag: "HackCon" },
      { tag: "Conference" },
      { tag: "Community" },
      { tag: "GitHub" },
      { tag: "Education" },
      { tag: "MLH Fellowship" },
    ],
    timeline_card_color: "cyan.400",
  },
];

export { timelineDetails };
